In [2]:
#Gauss Elimination
import numpy as np
import matplotlib.pyplot as plt

arr=np.array([[3,-2,5],[4,5,8],[45,1,2]])
b=np.array([2,4,5])
n=len(b)
x=np.zeros(n)
#elimination
for k in range(n-1):
    for i in range(k+1,n):
        factor=arr[k,k]/arr[i,k]
        for j in range(k,n):
            arr[i,j]=arr[k,j]-arr[i,j]*factor
        b[i]=b[k]-b[i]*factor
print(arr)
print(b)


[[  3  -2   5]
 [  0  -5  -1]
 [  0   0 -11]]
[ 2 -1 -3]


In [4]:
#Gauss Elimination
import numpy as np
import matplotlib.pyplot as plt

arr=np.array([[3,-2,5],[4,5,8],[0,1,2]])
b=np.array([2,4,5])
n=len(b)
x=np.zeros(n)
#elimination
for k in range(n-1):
    for i in range(k+1,n):
        if arr[i,k]==0:
            continue
        factor=arr[k,k]/arr[i,k]
        for j in range(k,n):
            arr[i,j]=arr[k,j]-arr[i,j]*factor
        b[i]=b[k]-b[i]*factor
print(arr)
print(b)


[[ 3 -2  5]
 [ 0 -5 -1]
 [ 0  0  9]]
[ 2 -1 24]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
A=np.array([2,0],[0,1])
x=np.array([1],[1])
b=np.dot(A,x)


In [2]:
def GaussSeidel(A,b,es=1.e-7,maxit=50):
    n,m=np.shape(A)
    if n!=m:
        return "not sq matrix"
    C=np.zeros((n,n))
    x=np.zeros((n,1))
    for i in range(n): 
        for j in range(n):
            if i!=j:
                C[i,j]=A[i,j]
    d=np.zeros((n,1))
    